name: Keyfactor Bootstrap Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize, edited, reopened]
  push:
  create:
    branches:
      - 'release-*.*'

jobs:
  call-starter-workflow:
    uses: keyfactor/actions/.github/workflows/starter.yml@v4
    with:
      command_token_url: ${{ vars.COMMAND_TOKEN_URL }}
      command_hostname: ${{ vars.COMMAND_HOSTNAME }}
      command_base_api_path: ${{ vars.COMMAND_API_PATH }}
    secrets:
      token: ${{ secrets.V2BUILDTOKEN}}
      gpg_key: ${{ secrets.KF_GPG_PRIVATE_KEY }}
      gpg_pass: ${{ secrets.KF_GPG_PASSPHRASE }}
      scan_token: ${{ secrets.SAST_TOKEN }}
      entra_username: ${{ secrets.DOCTOOL_ENTRA_USERNAME }}
      entra_password: ${{ secrets.DOCTOOL_ENTRA_PASSWD }}
      command_client_id: ${{ secrets.COMMAND_CLIENT_ID }}
      command_client_secret: ${{ secrets.COMMAND_CLIENT_SECRET }}